include:
  - modules/transmission/compose.yaml
  - modules/radarr/compose.yaml
  - modules/sonarr/compose.yaml
  - modules/audiobookshelf/compose.yaml
  - modules/lidarr/compose.yaml
  - modules/prowlarr/compose.yaml
  - modules/flaresolverr/compose.yaml
  - modules/home-assistant/compose.yaml
  - modules/portainer/compose.yaml
  - modules/jellyfin/compose.yaml
  - modules/watchtower/compose.yaml

services:
  # This file primarily serves as an entry point to include all modules.
  # Individual service configurations are located in their respective module folders.
  {}
